# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: web-service
  description: Nginx Web 服务模板
  icon: https://www.svgrepo.com/show/373924/nginx.svg
spec:
  variables:
    - key: DOMAIN
      name: 域名
      description: 绑定域名
      type: DOMAIN
    - key: SS_PASSWORD
      name: 密钥
      description: Base64 密钥 (openssl rand -base64 32)
      type: STRING

  services:
    - name: backend
      icon: https://www.svgrepo.com/show/452210/go.svg
      template: PREBUILT
      spec:
        source:
          image: teddysun/xray:latest
        ports:
          - id: service
            port: 1080
            type: HTTP
        env:
          SS_PASSWORD:
            default: ${SS_PASSWORD}
        configs:
          - path: /etc/xray/config.json
            template: |
              {
                "inbounds": [
                  {
                    "port": 1080,
                    "protocol": "shadowsocks",
                    "settings": {
                      "method": "2022-blake3-aes-256-gcm",
                      "password": "${SS_PASSWORD}",
                      "network": "tcp,udp"
                    },
                    "streamSettings": {
                      "network": "ws",
                      "wsSettings": {
                        "path": "/ws"
                      }
                    }
                  }
                ],
                "outbounds": [
                  {
                    "protocol": "freedom"
                  }
                ]
              }

    - name: nginx
      icon: https://www.svgrepo.com/show/373924/nginx.svg
      template: PREBUILT
      spec:
        source:
          image: nginx:alpine
        domainKey: DOMAIN
        ports:
          - id: web
            port: 80
            type: HTTP
        env:
          DOMAIN:
            default: ${DOMAIN}
        configs:
          - path: /etc/nginx/conf.d/default.conf
            template: |
              server {
                  listen 80;
                  server_name _;

                  location / {
                      default_type text/html;
                      return 200 '<!DOCTYPE html><html><head><title>Welcome</title></head><body><h1>Welcome to nginx!</h1></body></html>';
                  }

                  location /ws {
                      proxy_pass http://backend.zeabur.internal:1080;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection "upgrade";
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_connect_timeout 60s;
                      proxy_read_timeout 86400s;
                      proxy_send_timeout 60s;
                  }
              }

localization:
  zh-CN:
    description: Nginx Web 服务模板
